= SPAN GENERATOR

== OVERVIEW

Spans are the footprints to find the path that requests have followed to get their work done.
These spans contain useful information to detect problems in components or detect problems in connections. But also it might discover new components in the playground as many other detections which might come to your head.

The aim of this project is to create those spans which go through different operations in a train of microservices,
quickly and exporting them to different sinks, so to make a test scenario in which you find confident to get your results.

== WHEN IS IT USEFUL?

Working in observability and dealing with spans, this help to have a dataset which is constant and might help in your development process.

Also it helps to generate spans consume by collectors or redirected to message queues like `kafka` to be consumed by some custom application or tool, testing so their capabilities.

Up to now we have injected limited number of files into `kafka` producers or REST apis to have the content in the other end;
or we have created a number of instrumented sample applications which produce those spans;
or using `tracers` which generate spans base in their API building.

In here the scenarios are mocking. It contains a clock which fits with the need to move accordingly. Which let us generate a big number of spans and try to test loads of spans.

We might say this is useful when you want tasks generating their footprints,
without having those running anywhere and taking over how fast they are invoked and how often they introduce an error.

== HOW TO USE IT?
